services:
  db:
    image: postgres:15-alpine
    container_name: "cd-judge-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=cd-judge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U dev -d cd-judge"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  redis:
    image: redis:latest
    container_name: cd-judge-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
